version: '3'

services:
  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - 6379:6379
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf:rw
      - ./data:/data:rw
    command:
      /bin/bash -c "redis-server /usr/local/etc/redis/redis.conf "
#  Etcd:
#    image: "quay.io/coreos/etcd:v3.5.5"
#    environment:
#      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
#      - ETCD_ADVERTISE_CLIENT_URLS=http://0.0.0.0:2379
#      - ETCDCTL_API=3
#    ports:
#      - 23790:2379
#  jaeger:
#    image: jaegertracing/all-in-one:latest
#    ports:
#      - "6831:6831/udp"
#      - "16686:16686"
