// Code generated by hertz generator.

package video

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io/ioutil"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"time"

	"github.com/simplecolding/douyin/hertz-server/biz/redis"
	"github.com/simplecolding/douyin/hertz-server/biz/utils"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	"github.com/disintegration/imaging"
	video "github.com/simplecolding/douyin/hertz-server/biz/model/hertz/video"
	"github.com/simplecolding/douyin/hertz-server/biz/orm/dal"
	"github.com/simplecolding/douyin/hertz-server/biz/orm/model"
	ffmpeg "github.com/u2takey/ffmpeg-go"
)

// VideoPublish .
// @router /douyin/publish/action [POST]
func VideoPublish(ctx context.Context, c *app.RequestContext) {
	//req.Data type : bytes
	var err error
	//var r video.PublishActionRequest
	var r video.DouyinPublishActionRequest
	var resp video.DouyinPublishActionResponse
	var byteContainer []byte

	r.Token, _ = c.GetPostForm("token")
	r.Title, _ = c.GetPostForm("title")
	fileHeader, err := c.FormFile("data")
	if err != nil {
		panic(err)
	}
	open, err := fileHeader.Open()
	if err != nil {
		panic(err)
	}
	// 读取文件到字节数组
	fileRaw, err := ioutil.ReadAll(open)
	if err != nil {
		panic(err)
	}

	byteContainer = fileRaw
	flag, userName, uid, _ := utils.Auth(ctx, r.Token)
	if !flag {
		c.JSON(consts.StatusBadRequest, "token错误")
		return
	}
	// gzipWriter.Write(byteContainer)
	fileName := strconv.FormatInt(time.Now().Unix(), 10) + userName
	if err != nil {
		println("get filetype failed")
		return
	}
	filePath := filepath.Join("./biz/public", fileName+".mp4")

	newFile, err := os.Create(filePath)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		println("create file failed")
		return
	}
	defer newFile.Close()
	if _, err := newFile.Write(byteContainer); err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		println("write file failed")
		return
	}

	playUrl := utils.PlayURL + fileName + ".mp4"
	println("playUrl: ", playUrl)
	// title := "test"
	// test
	// 生成封面
	coverPath := "./biz/public/cover/" + fileName
	coverPath, err = GetSnapshot(filePath, coverPath, 1)
	var coverUrl string
	if err != nil {
		coverUrl = utils.CoverTestURL
	} else {
		coverUrl = utils.CoverURL + fileName + ".png"
	}
	var cstSh, _ = time.LoadLocation("Asia/Shanghai")
	t := time.Now().In(cstSh)
	err = dal.Video.WithContext(ctx).Create(&model.Video{UID: uid, PlayURL: playUrl, CoverURL: coverUrl,
		CreatedAt: t})

	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		println("write to database failed")
		return
	}
	println(filePath)
	resp.StatusCode = 0
	resp.StatusMsg = "success"

	c.JSON(consts.StatusOK, resp)
}

// GetPublishList .
// @router /douyin/publish/list [GET]
func GetPublishList(ctx context.Context, c *app.RequestContext) {
	var err error
	var req video.DouyinPublishListRequest
	resp := new(video.DouyinFavoriteListResponse)

	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}
	// auth
	flag, _, uid, uidString := utils.Auth(ctx, req.Token)
	if !flag {
		c.JSON(consts.StatusBadRequest, "token错误")
		return
	}

	// todo 需要limit8?分页??
	data, err := dal.Video.Where(dal.Video.UID.Eq(uid)).Find()
	if err != nil {
		println("query database failed")
		c.JSON(consts.StatusBadRequest, "query database failed")
		return
	}
	// query userinfo
	userInfo := VideoQueryUser(uid)

	var v []*video.Video
	redisCtx, cancel := context.WithTimeout(context.Background(), 500*time.Hour)
	defer cancel()
	// 添加redis缓存
	rbytes := []byte(redis.RD.Get(redisCtx, uidString).Val())

	if len(rbytes) != 0 {
		json.Unmarshal(rbytes, &v)
	} else {
		for _, d := range data {
			vid := d.Vid
			var tmp video.Video
			tmp.Id = d.Vid
			tmp.CoverUrl = d.PlayURL
			tmp.PlayUrl = d.PlayURL
			tmp.CoverUrl = d.CoverURL
			tmp.FavoriteCount, _ = dal.Video.Where(dal.Video.Vid.Eq(vid)).Count()
			tmp.CommentCount, _ = dal.Comment.Where(dal.Comment.Vid.Eq(vid)).Count()
			fav, _ := dal.Favorite.CountVidAndUid(vid, uid)
			tmp.IsFavorite = len(fav) >= 1
			tmp.Title = d.Title
			tmp.Author = &userInfo
			v = append(v, &tmp)
		}
		data, _ := json.Marshal(v)
		redis.RD.Set(redisCtx, uidString, data, time.Second*20)
	}

	resp.VideoList = v
	resp.StatusCode = 0
	resp.StatusMsg = "success"
	c.JSON(consts.StatusOK, resp)
}

// GetFeed .
// @router /douyin/feed [GET]
func GetFeed(ctx context.Context, c *app.RequestContext) {
	var err error
	var req video.DouyinFeedRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}
	// 鉴权,如果没有token的话uid为0
	_, _, uid, _ := utils.Auth(ctx, req.Token)
	resp := new(video.DouyinFeedResponse)
	// todo
	// 30 videos for a single time
	limit := 30
	// Not test

	redisCtx, cancel := context.WithTimeout(context.Background(), 500*time.Hour)
	defer cancel()
	var v []*video.Video

	keyString := "videoList"
	rbytes := []byte(redis.RD.Get(redisCtx, keyString).Val())
	// var rbytes []byte
	if len(rbytes) != 0 {
		json.Unmarshal(rbytes, &v)
		// fmt.Print("get from redis", v)
	} else {
		data, err := dal.Video.Order(dal.Video.CreatedAt.Desc()).Limit(limit).Find()
		if err != nil {
			println("query database failed")
			return
		}
		for _, d := range data {
			var tmp video.Video
			tmp.Id = d.Vid
			tmp.CoverUrl = d.CoverURL
			tmp.PlayUrl = d.PlayURL
			tmp.Title = d.Title
			tmp.FavoriteCount, _ = dal.Favorite.Where(dal.Favorite.Vid.Eq(d.Vid)).Count()
			tmp.CommentCount, _ = dal.Comment.Where(dal.Comment.Vid.Eq(d.Vid)).Count()
			//fav, _ := dal.Favorite.CountVidAndUid(d.Vid, d.UID)
			fav, _ := dal.Favorite.Where(dal.Favorite.Vid.Eq(d.Vid)).Where(dal.Favorite.UID.Eq(uid)).Count()
			tmp.IsFavorite = fav >= 1
			tmp.Title = d.Title
			userInfo := VideoQueryUser(d.UID)
			tmp.Author = &userInfo
			v = append(v, &tmp)
		}
		bytes, _ := json.Marshal(v)
		redis.RD.Set(redisCtx, keyString, bytes, time.Second*30)
	}

	resp.VideoList = v
	resp.StatusCode = 0
	resp.StatusMsg = "success"
	c.JSON(consts.StatusOK, resp)
}

// VideoQueryUser query userinfo
func VideoQueryUser(uid int64) video.User {
	dal.UserAuth.Where(dal.UserAuth.UID.Eq(uid))
	totalFavorited := int64(0)
	v, err := dal.Video.Where(dal.Video.UID.Eq(uid)).Find()
	for _, t := range v {
		tmpcount, _ := dal.Favorite.Where(dal.Favorite.Vid.Eq(t.Vid)).Count()
		totalFavorited += tmpcount
	}
	// 低性能代码
	workCount, _ := dal.Video.Where(dal.Video.UID.Eq(uid)).Count()
	favoriteCount, _ := dal.Favorite.Where(dal.Favorite.UID.Eq(uid)).Count()
	userInfoDB, err := dal.UserAuth.Where(dal.UserAuth.UID.Eq(uid)).First()
	if err != nil {
		println("database err")
	}
	userInfoDB.WorkCount = workCount
	userInfoDB.FavoriteCount = favoriteCount
	userInfoDB.TotalFavorite = strconv.FormatInt(totalFavorited, 10)
	dal.UserAuth.Save(userInfoDB)

	return video.User{
		Id:              userInfoDB.UID,
		Name:            userInfoDB.UserName,
		FollowCount:     userInfoDB.FollowCount,
		IsFollow:        userInfoDB.IsFollow,
		Avatar:          userInfoDB.Avatar,
		BackgroundImage: userInfoDB.BackgroundImage,
		Signature:       userInfoDB.Signature,
		TotalFavorited:  userInfoDB.TotalFavorite,
		WorkCount:       userInfoDB.WorkCount,
		FavoriteCount:   userInfoDB.FavoriteCount,
	}
}

func GetSnapshot(videoPath, snapshotPath string, frameNum int) (snapshotName string, err error) {
	defer recover()
	buf := bytes.NewBuffer(nil)
	err = ffmpeg.Input(videoPath).
		Filter("select", ffmpeg.Args{fmt.Sprintf("gte(n,%d)", frameNum)}).
		Output("pipe:", ffmpeg.KwArgs{"vframes": 1, "format": "image2", "vcodec": "mjpeg"}).
		WithOutput(buf, os.Stdout).
		Run()
	if err != nil {
		print("生成缩略图失败：", err)
		return "", err
	}

	img, err := imaging.Decode(buf)
	if err != nil {
		print("生成缩略图失败：", err)
		return "", err
	}

	err = imaging.Save(img, snapshotPath+".png")
	if err != nil {
		print("生成缩略图失败：", err)
		return "", err
	}

	names := strings.Split(snapshotPath, "\\")
	snapshotName = names[len(names)-1] + ".png"
	return
}
